[template]
include = ["Cargo.toml", "Cargo.lock", ".github/workflows/*", "*.rs"]

[placeholders.itch_username]
prompt = "Enter your itch.io username. Leave blank to disable itch.io upload."
type = "string"
default = ""

[conditional.'itch_username != ""'.placeholders]
itch_project = { type = "string", prompt = "Enter the itch.io project name. Leave blank to use the project-name.", default="" }
